class JOBS {
    constructor() {
        console.log('Loading JOBS...');
        var xhttp = new XMLHttpRequest();
        xhttp.open('GET', 'http://127.0.0.1:31333/test', false);
        xhttp.send();
        if (xhttp.status === 200) {
            var resp = JSON.parse(xhttp.responseText);
            this.data = resp['value'].map(function (i, index) {
                let oJOBS = {
                    ID: index,
                    JOBNUM: i.JOBNUM,
                    JOBTIME: i.JOBTIME,
                    JOBTIMEPERCENTROUND: i.JOBTIMEPERCENTROUND,
                    JOBTIMETYPEDES: i.JOBTIMETYPEDES,
                    JOBTIMETYPENAME: i.JOBTIMETYPENAME,
                    JOBTYPE: i.JOBTYPE,
                    LEAVEDATE: i.LEAVEDATE,
                    LEAVEREASONDES: i.LEAVEREASONDES,
                    LEAVEREASONNAME: i.LEAVEREASONNAME,
                    LOCATION: i.LOCATION,
                    NUSERLOGIN: i.NUSERLOGIN,
                    OVERTIME: i.OVERTIME,
                    OWNERLOGIN: i.OWNERLOGIN,
                    POSITIONCODE: i.POSITIONCODE,
                    POSITIONDES: i.POSITIONDES,
                    RECRUITMENTREMARKS: i.RECRUITMENTREMARKS,
                    RECRUITMETHODDES: i.RECRUITMETHODDES,
                    RECRUITREASON: i.RECRUITREASON,
                    REQDATE: i.REQDATE,
                    SNAME: i.SNAME,
                    SSNAME: i.SSNAME,
                    STATDES: i.STATDES,
                    SUBUSERID: i.SUBUSERID,
                    UDATE: i.UDATE,
                    UFLAG: i.UFLAG,
                    USERID: i.USERID,
                    USERLOGIN: i.USERLOGIN,
                    WORKDAYSNUM: i.WORKDAYSNUM,
                    WORKHOURS: i.WORKHOURS,
                    ZCLA_AFTERAPPFLAG: i.ZCLA_AFTERAPPFLAG,
                    ZCLA_CLOSENOTE: i.ZCLA_CLOSENOTE,
                    ZCLA_EXTERNALLINK: i.ZCLA_EXTERNALLINK,
                    ZCLA_SHOWINPORTAL: i.ZCLA_SHOWINPORTAL,
                    ZCLA_SHOWPORTAL: i.ZCLA_SHOWPORTAL,
                    ZCLA_TEMPLATE: i.ZCLA_TEMPLATE,
                    ZGEM_APPLICANTS: i.ZGEM_APPLICANTS,
                    ZGEM_DIREMAIL: i.ZGEM_DIREMAIL,
                    ZGEM_DIRTOAPPFULL: i.ZGEM_DIRTOAPPFULL,
                    ZGEM_DIRTOAPPNAME: i.ZGEM_DIRTOAPPNAME,
                    ZGEM_HIRINGMANEMAIL: i.ZGEM_HIRINGMANEMAIL,
                    ZGEM_HRMANNAME: i.ZGEM_HRMANNAME,
                    BRANCHNAME: i.BRANCHNAME,
                    BUDCODE: i.BUDCODE,
                    BUDNAME: i.BUDNAME,
                    CANCELED: i.CANCELED,
                    CODEDES: i.CODEDES,
                    CODENAME: i.CODENAME,
                    COSTCDES: i.COSTCDES,
                    COSTCNAME: i.COSTCNAME,
                    COUNTRYNAME: i.COUNTRYNAME,
                    CRMNUM: i.CRMNUM,
                    CURDATE: i.CURDATE,
                    CUSTCAMPTYPEDES: i.CUSTCAMPTYPEDES,
                    DEPTDES: i.DEPTDES,
                    DEPTNAME: i.DEPTNAME,
                    DISCREET: i.DISCREET,
                    DISTRICTDES: i.DISTRICTDES,
                    DIVISIONDES: i.DIVISIONDES,
                    DIVISIONNAME: i.DIVISIONNAME,
                    DURATION: i.DURATION,
                    EXTFILEFLAG: i.EXTFILEFLAG,
                    FATJOBDES: i.FATJOBDES,
                    FATJOBNUM: i.FATJOBNUM,
                    FILLED: i.FILLED,
                    HOLD: i.HOLD,
                    ACTUALJOBPERCENT: i.ACTUALJOBPERCENT,
                    ACTUALJOBTIME: i.ACTUALJOBTIME,
                    JOBDES: i.JOBDES,
                    BRANCHDES: i.BRANCHDES,
                    JOBCANDIDATES_SUBFORM : i.JOBCANDIDATES_SUBFORM.map(function (i, index) {
                        let oJOBCANDIDATES = {
                            ID: index,
                            JOBTIMEPERCENT: i.JOBTIMEPERCENT,
                            OWNERLOGIN: i.OWNERLOGIN,
                            PHONE: i.PHONE,
                            SNAME: i.SNAME,
                            STATDES: i.STATDES,
                            STATUSCODE: i.STATUSCODE,
                            UDATE: i.UDATE,
                            USERB: i.USERB,
                            USERLOGIN: i.USERLOGIN,
                            ZCLA_ABOVEAGE: i.ZCLA_ABOVEAGE,
                            ZCLA_DRIVINGLICENSE: i.ZCLA_DRIVINGLICENSE,
                            ZCLA_EXPERIENCE: i.ZCLA_EXPERIENCE,
                            ZCLA_EXTFILENAME: i.ZCLA_EXTFILENAME,
                            ZCLA_EXTFILENAMEA: i.ZCLA_EXTFILENAMEA,
                            ZCLA_NOTICE: i.ZCLA_NOTICE,
                            ZCLA_PRIVACY: i.ZCLA_PRIVACY,
                            ZCLA_QUALIFICATIONS: i.ZCLA_QUALIFICATIONS,
                            ZCLA_RECSENT: i.ZCLA_RECSENT,
                            ZCLA_REFFERALDES: i.ZCLA_REFFERALDES,
                            ZCLA_REJSENT: i.ZCLA_REJSENT,
                            ZCLA_WORKINUK: i.ZCLA_WORKINUK,
                            ZGEM_AGENCY: i.ZGEM_AGENCY,
                            ZGEM_AGENCYEMAIL: i.ZGEM_AGENCYEMAIL,
                            ZGEM_FILTER: i.ZGEM_FILTER,
                            ZGEM_HIRINGMANEMAIL: i.ZGEM_HIRINGMANEMAIL,
                            ZGEM_HIRINMANLOGIN: i.ZGEM_HIRINMANLOGIN,
                            ZGEM_REASON: i.ZGEM_REASON,
                            ZGEM_SUPDES: i.ZGEM_SUPDES,
                            EMAIL: i.EMAIL,
                            EMPUSERID: i.EMPUSERID,
                            FILLEDAT: i.FILLEDAT,
                            IDNUMBER: i.IDNUMBER,
                            CANDUSERID: i.CANDUSERID,
                            CELLPHONE: i.CELLPHONE,
                            CURDATE: i.CURDATE,
                            JOBCANDNUM: i.JOBCANDNUM,
                        }
                        return oJOBCANDIDATES;
                    }),
                    JOBSTEXTB_SUBFORM : i.JOBSTEXTB_SUBFORM.map(function (i, index) {
                        let oJOBSTEXTB = {
                            ID: index,
                            TEXT: i.TEXT,
                        }
                        return oJOBSTEXTB;
                    }),
                }
                return oJOBS;
            }),;
        }
    }
}
